# Configuration

# Site settings
abbr: GNDEM
title: Global Network of Domestic Election Monitors
email: gndem09@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The Global Network of Domestic Election Monitors connects over 245 regional networks and individual nonpartisan citizen observation groups to share best practices and further our common aspirations for representative, responsive, transparent, democratic governance.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gndem.org" # the base hostname & protocol for your site, e.g. http://example.com

facebook_username: GNDEM
twitter_username: gndemexchanges
cloudinary_url: https://res.cloudinary.com/gndem/image/upload/

show_excerpts: true
date_format: "%B %-d, %Y"
show_tags: false

collections:
  posts:
    title: Stories
    output: true
  members:
    title: Members
    output: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/stories/:slug/"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
sass: 
  style: compressed
  sourcemap: never

languages: ["en", "es", "fr", "ar", "ru"]
default_lang: "en"
exclude_from_localization: ["assets","javascript", "images", "css"]
parallel_localization: true

jekyll-archives:
  enabled: ['tags']
  layout: 'archives'
  permalinks:
    tag: '/tag/:name/'

plugins:
  - jekyll-archives

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/